### ISSUE TITLE
Incorrect error stack

### ISSUE THREAD

**Issue by ivantsov** [gaearon/react-transform-catch-errors#10]
When error occurs in `render` method, `console.error(err)` will be called and it will show wrong callstack:
![wrong-stack](https://cloud.githubusercontent.com/assets/1555792/10099656/3a421bfa-63a5-11e5-8a36-6b65604819f4.jpg)

I think you should use `console.error(err.stack)` instead. It will produce correct call stack:
![right-stack](https://cloud.githubusercontent.com/assets/1555792/10099667/4aa75956-63a5-11e5-9ad1-b70e0ec70517.jpg)

**Comment by gaearon** [comment]
Woah. Wanna make a PR? Does this work in every browser and with different `devtool` configurations?

**Comment by ivantsov** [comment]
Okay, I'll check it out in different environments and if my solution works - will make a PR.

**Comment by ivantsov** [comment]
Hmm, I guess it was my fault... There is an '(...)':
![wrong-stack](https://cloud.githubusercontent.com/assets/1555792/10128614/47c6f7c0-65ce-11e5-9858-bedbbc498861.jpg)
The right callstack will be shown when you click it:
![right-stack](https://cloud.githubusercontent.com/assets/1555792/10128615/49eab64a-65ce-11e5-92d8-0a17fa62b3c1.jpg)

Maybe it's not obvious and you should show `err.stack` but it's up to you because I don't really know how many people are aware of this feature. Maybe I'm the only one who didn't know :)

**Comment by idolize** [comment]
@ShpuntiK I was likewise very confused by this problem. I don't think the default stack shown is very helpful unless you are working to debug `react-transform-catch-errors` itself.

PR would still be worthwhile in my opinion.

**Comment by gaearon** [comment]
Happy to accept a PR fixing this.

**Comment by ivantsov** [comment]
Should be resolved in https://github.com/gaearon/react-transform-catch-errors/pull/12. Tested in chrome and firefox.

**Comment by gaearon** [comment]
Fixed by #12, will be out in next release.

**Comment by gaearon** [comment]
Out in 1.0.1 implemented in a slightly different way so it's compatible with Firefox too.
