### ISSUE TITLE
Server-side code transpiling issues with redbox-react

### ISSUE THREAD

**Issue by joseph887** [gaearon/react-transform-catch-errors#2]
I use babel to transpile my server-side code, but as window is not defined on the server, adding the react-transform-catch-errors transformation to .babelrc throws an error. The server.js example given [here](https://github.com/gaearon/flux-react-router-example/commit/53e5ad5ec10974d195b002a3a07a3239d1478b7b#diff-78c12f5adc1848d13b1c6f07055d996eL1) just uses ES5 syntax, but I would rather have babel transpile my ES6 code. 

Is there a good way around this issue? I've been fiddling around with the rc file and require hooks but didn't find a way to make this work.

**Comment by netfishx** [comment]
me too

**Comment by netfishx** [comment]
in redbox-react , use window and document. when render in server-side ,they all undefined.

**Comment by gaearon** [comment]
You don't need to use `redbox-react`.
It's in configuration precisely because it is configurable.

See, for example, https://github.com/aulizko/delicate-error-reporter, as an alternative.
Any issues with `redbox-react` should be reported in its repo.

**Comment by jedwards1211** [comment]
Do you know if `redbox-react` breaks source maps too?  We seem to be seeing this issue: https://github.com/jedwards1211/meteor-webpack-react/issues/40
I haven't delved into it too deeply yet

**Comment by jedwards1211** [comment]
Just confirmed we have the source map issue with `delicate-error-reporter` too.  We see `ProxyClass` instead of our own component name in the stack traces, and the console stack trace links directly to the webpack bundle instead of the original source.

**Comment by gaearon** [comment]
@jedwards1211 How is the source map question related to this issue?

**Comment by jedwards1211** [comment]
Sorry, it's not very related, I just looked at this issue first because "transpiling issue" might describe what I'm seeing

**Comment by gaearon** [comment]
See https://github.com/jedwards1211/meteor-webpack-react/issues/40#issuecomment-140200132.
