### ISSUE TITLE
Need to catch errors in other lifecycle methods not only in render.

### ISSUE THREAD

**Issue by aN0obIs** [gaearon/react-transform-catch-errors#22]
I've currently implemented some changes to resolve this in 
https://github.com/aN0obIs/react-transform-catch-errors. 

And only after that I've saw that there already is one pull request which address same issue. (https://github.com/gaearon/react-transform-catch-errors/pull/11)

I think that this functionality should be included in.

**Comment by patrickporto** [comment]
:+1:

**Comment by gaearon** [comment]
I plan to deprecate this package later because React v15 support for error boundaries should provide a nicer solution to this. So I don’t plan to get something like this in, as React will support it out of the box. Thanks!
