### ISSUE TITLE
.babelrc in npm installation

### ISSUE THREAD

**Issue by itsjef** [gaearon/react-transform-catch-errors#23]
I tried to install _react-transform-catch-errors_ using `npm install`.

However, the _.babelrc_ in the installation still had the **_{stage:0}_** option which is now deprecated.

Please fix this.

**Comment by gaearon** [comment]
Why does this affect you? You shouldn't worry about what build tools or configs are used by third party modules such as this one.

**Comment by gaearon** [comment]
Fixed in 1.0.2. But if this was a problem, this means you are transpiling node_modules with Babel, which I think you shouldn't do. This just means wasted compilation time & other potential issues.
