### ISSUE TITLE
Broken source maps?

### ISSUE THREAD

**Issue by jedwards1211** [gaearon/react-transform-catch-errors#3]
I'm still confused about what's going on here, but when I use this with redbox-react or delicate-error-reporter, the source maps don't quite seem to work. Here's a screenshot. You can see that it shows ProxyClass instead of App.jsx. Also the error printed to the console links directly into the webpack bundle instead of the original source.

![image](https://cloud.githubusercontent.com/assets/1448194/9829661/a17d5622-58d3-11e5-9e5b-7e1de332a090.png)

This was first brought to my attention here: jedwards1211/meteor-webpack-react#40

Reproducible with the latest version of meteor-webpack-react, if you change `App.jsx`'s `render` to throw an Error: jedwards1211/meteor-webpack-react@353f8c4

We are doing one weird thing in that project: serving the webpack bundle from localhost:9090 whereas the rest of the page is served by Meteor from localhost:3000.

Any ideas what would be the issue?

**Comment by gaearon** [comment]
Please report this in [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate). This project has nothing to do with source maps, or proxying—if you take a look at its source, all it does is replace `render` method on the prototype. It can't possibly have any relation to the problems you described.

**Comment by jedwards1211** [comment]
Okay, will do!

**Comment by gaearon** [comment]
See https://github.com/jedwards1211/meteor-webpack-react/issues/40#issuecomment-140200132.
