### ISSUE TITLE
Would be useful to turn off in test env as well as production

### ISSUE THREAD

**Issue by hoegrammer** [gaearon/react-transform-catch-errors#6]
When running unit tests the errors are caught which means you don't get an informative stack trace. Might it be useful to treat NODE_ENV=test the same as production, or perhaps to allow the user to set options as to which envs to catch errors in?

**Comment by gaearon** [comment]
We now explicitly suggest using `env` in `.babelrc`: https://github.com/gaearon/babel-plugin-react-transform/pull/13. Feel free to send a PR to change this README too.
